try uploading to anaconda.org (#2123)
* try uploading to anaconda.org

* gcp and anaconda-client

* another token attempt

* right dir separator?

* another path?

* order args

* show silent fails

* extra dep

* quicker

* right path?

* right path 2?

* right path 3

* right path 5

* right path 6?

* it works

* tidyup

diff --git a/.azure-pipelines/azure-pipelines-windows.yml b/.azure-pipelines/azure-pipelines-windows.yml
--- a/.azure-pipelines/azure-pipelines-windows.yml
+++ b/.azure-pipelines/azure-pipelines-windows.yml
@@ -10,7 +10,7 @@ jobs:
       llvm.version: '11.0.0'
       mkl.version: '2019.1'
       cmake.build_type: 'Release'
-      conda.build: true
+      conda.build: false
       MKL_CBWR: AVX
       PYTHON_VERSION: '3.8'
     steps:
@@ -112,6 +112,7 @@ jobs:
       # Note: c-f eigen has Config.cmake file
       - script: |
           conda install cmake ^
+                        anaconda-project ^
                         conda-build ^
                         conda-forge::eigen ^
                         conda-verify ^
@@ -127,6 +128,7 @@ jobs:
                         pytest-xdist ^
                         python=%PYTHON_VERSION% ^
                         psi4/label/dev::dftd3 ^
+                        psi4/label/dev::gcp ^
                         conda-forge::gau2grid ^
                         psi4/label/dev::libint2 ^
                         conda-forge::libxc ^
@@ -135,6 +137,9 @@ jobs:
                         conda-forge::qcelemental ^
                         conda-forge::qcengine
           pip install git+https://github.com/i-pi/i-pi.git@master-py3
+          conda install --only-deps anaconda-client
+          pip install git+https://github.com/loriab/anaconda-client.git@upload-catch-silent
+          which anaconda
           conda list
         displayName: "Install conda packages"
 
@@ -249,12 +254,34 @@ jobs:
           conda build --python %PYTHON_VERSION% ^
                       conda\win
           copy /y C:\tools\miniconda3\conda-bld\win-64\psi4-*.bz2 $(Build.ArtifactStagingDirectory)
-        condition: and(succeeded(), eq(variables['conda.build'], 'true'))
+        condition: and(succeeded(), or(eq(variables['conda.build'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
         displayName: "Build Psi4 package"
 
       # Publish package
       - task: PublishBuildArtifacts@1
         inputs:
           artifactName: conda
-        condition: and(succeeded(), eq(variables['conda.build'], 'true'))
+        condition: and(succeeded(), or(eq(variables['conda.build'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
         displayName: "Publish Psi4 package"
+
+      # Upload package
+      # * use same ANACONDA_TOKEN generated on anaconda.org for GHA and save it in Azure DevOps
+      #   at /psi4/psi4/Pipelines/psi4.psi4 -> Edit button -> Variables button -> new secret var `conda.anaconda_org_token`.
+      # * error handling may need tweaking as I don't know if failure to upload for lack of space (`echo $?`=1) will fail the workflow.
+      - bash: |
+          set -e
+          ls -l /c/tools/miniconda3/conda-bld/win-64/*.tar.bz2
+          echo "Using the mapped env var for this task works and is recommended: $(conda.anaconda_org_token)"
+          anaconda whoami
+          anaconda \
+            --verbose \
+           upload \
+            --label dev \
+            --skip \
+            /c/tools/miniconda3/conda-bld/win-64/*.tar.bz2
+          echo $?
+        env:
+          ANACONDA_API_TOKEN: $(conda.anaconda_org_token)
+        condition: and(succeeded(), or(eq(variables['conda.build'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
+        displayName: "Upload Psi4 package to anaconda.org"
+
